"""Product-specific copy and illustrative states for protected pipeline health surfaces."""

PIPELINE_HEALTH = {
    "public-sector": {
        "product_name": "Public Sector HossAgent",
        "division": "Pursuit intelligence",
        "glyph": "P",
        "theme": "public",
        "headline": "Know where a pursuit is healthy—and where the evidence chain breaks.",
        "lede": "Inspect every stage from source-backed program signal to an operator-ready pursuit packet. Weak access, unsupported funding, and invented partner posture remain visible instead of becoming pipeline theater.",
        "decision": "Does this signal deserve bounded pursuit effort?",
        "health_label": "Evidence review",
        "health_value": "82%",
        "health_note": "2 stages need operator attention",
        "guardrail": "No pursuit moves forward without corroborated need, a credible access path, and named operator authority.",
        "artifact": "Pursuit packet",
        "demo_url": "/public-sector/demo",
        "stages": [
            ("01", "Source intake", "18 signals", "14 corroborated", "healthy", "Healthy"),
            ("02", "Opportunity resolution", "14 records", "2 identity conflicts", "watch", "Review"),
            ("03", "Qualification", "12 candidates", "9 funded needs", "healthy", "Healthy"),
            ("04", "Partner posture", "9 pursuits", "3 access gaps", "blocked", "Blocked"),
            ("05", "Packet readiness", "6 packets", "4 operator-ready", "watch", "Review"),
        ],
        "checks": [
            ("Primary-source coverage", "14 / 18", "78%", "watch"),
            ("Funding corroborated", "9 / 12", "75%", "watch"),
            ("Access path named", "6 / 9", "67%", "blocked"),
            ("Decision owner assigned", "6 / 6", "100%", "healthy"),
        ],
        "blockers": [
            ("Atlas modernization", "Partner posture", "Access path is inferred, not verified", "Resolve or stop"),
            ("Harbor logistics", "Opportunity resolution", "Two agencies share the working title", "Disambiguate"),
            ("Cedar sustainment", "Packet readiness", "Funding source is older than 90 days", "Refresh evidence"),
        ],
        "repairs": {
            "Opportunity resolution": ("Re-resolve identities", "Canonical agency records selected; conflicting titles retained as aliases."),
            "Partner posture": ("Verify access paths", "Unsupported access claims isolated; only corroborated partner paths remain eligible."),
            "Packet readiness": ("Refresh stale evidence", "Funding evidence refreshed and incomplete packets held outside the release set."),
        },
    },
    "private-sector": {
        "product_name": "Private Sector HossAgent",
        "division": "Account intelligence",
        "glyph": "B2B",
        "theme": "private",
        "headline": "See whether an account motion is relevant before it becomes nuisance outbound.",
        "lede": "Follow a company signal through identity resolution, bounded pain hypothesis, readiness, buyer verification, and permitted channel review. The pipeline measures decision quality—not message volume.",
        "decision": "Is there a real buyer, a real reason now, and a safe motion?",
        "health_label": "Motion readiness",
        "health_value": "76%",
        "health_note": "Buyer and channel checks are constraining release",
        "guardrail": "No outbound until the company, relevant buyer, timing basis, and permitted channel are all verified.",
        "artifact": "Buyer-ready brief",
        "demo_url": "/private-sector/demo",
        "stages": [
            ("01", "Signal intake", "34 signals", "28 in policy", "healthy", "Healthy"),
            ("02", "Company resolution", "28 records", "26 exact matches", "healthy", "Healthy"),
            ("03", "Pain hypothesis", "26 accounts", "8 weak claims", "watch", "Review"),
            ("04", "Buyer verification", "18 accounts", "7 buyer gaps", "blocked", "Blocked"),
            ("05", "Motion readiness", "11 briefs", "8 releasable", "watch", "Review"),
        ],
        "checks": [
            ("Company exact match", "26 / 28", "93%", "healthy"),
            ("Timing basis sourced", "18 / 26", "69%", "watch"),
            ("Relevant buyer verified", "11 / 18", "61%", "blocked"),
            ("Permitted channel found", "8 / 11", "73%", "watch"),
        ],
        "blockers": [
            ("Northstar Foods", "Buyer verification", "Role is relevant; person is unverified", "Verify buyer"),
            ("Relay Commerce", "Pain hypothesis", "Expansion signal does not prove operational pain", "Narrow claim"),
            ("Blue Mesa Health", "Motion readiness", "No permitted contact channel found", "Hold motion"),
        ],
        "repairs": {
            "Pain hypothesis": ("Narrow unsupported claims", "Weak pain claims removed; remaining hypotheses are bounded to sourced signals."),
            "Buyer verification": ("Re-verify relevant buyers", "Unverified people removed and role-level gaps returned for operator review."),
            "Motion readiness": ("Recheck permitted channels", "Unsafe channels suppressed; releasable briefs now contain verified paths only."),
        },
    },
    "property-intelligence": {
        "product_name": "Property Intelligence",
        "division": "Owner intelligence",
        "glyph": "RE",
        "theme": "property",
        "headline": "Trace every property event to the right parcel, owner, and allowable next move.",
        "lede": "Monitor the resolution chain from primary event through parcel match, ownership provenance, channel verification, and operator approval. Ambiguity stops the motion instead of leaking into outreach.",
        "decision": "Is this the right property, the right owner, and the right channel?",
        "health_label": "Resolution health",
        "health_value": "88%",
        "health_note": "Ownership is strong; two channels require review",
        "guardrail": "No owner motion is released while parcel identity, ownership provenance, or channel permission remains ambiguous.",
        "artifact": "Owner-qualified brief",
        "demo_url": "/property-intelligence/demo",
        "stages": [
            ("01", "Event intake", "22 events", "21 primary records", "healthy", "Healthy"),
            ("02", "Parcel resolution", "21 events", "1 multi-parcel conflict", "watch", "Review"),
            ("03", "Ownership chain", "20 parcels", "18 current owners", "watch", "Review"),
            ("04", "Channel provenance", "18 owners", "2 unsafe channels", "blocked", "Blocked"),
            ("05", "Motion approval", "16 briefs", "15 operator-ready", "healthy", "Healthy"),
        ],
        "checks": [
            ("Primary event record", "21 / 22", "95%", "healthy"),
            ("Exact parcel match", "20 / 21", "95%", "healthy"),
            ("Current owner verified", "18 / 20", "90%", "watch"),
            ("Safe channel verified", "16 / 18", "89%", "watch"),
        ],
        "blockers": [
            ("Biscayne renovation", "Channel provenance", "Phone is present but source permission is unclear", "Hold channel"),
            ("Weston mixed-use", "Ownership chain", "Recent deed transfer is not yet corroborated", "Refresh deed"),
            ("Doral reroof", "Parcel resolution", "Permit address spans two adjacent parcels", "Resolve parcel"),
        ],
        "repairs": {
            "Parcel resolution": ("Re-run parcel matching", "Ambiguous address split into candidate parcels; exact match retained and conflict held."),
            "Ownership chain": ("Refresh ownership records", "Recent transfers rechecked; uncorroborated owner claims removed from the eligible set."),
            "Channel provenance": ("Revalidate channel permission", "Unclear phone sources suppressed; verified channels remain available for review."),
        },
    },
}
