"""Synthetic, customer-facing stories for the HossAgent product demo system."""

import json


PRODUCT_DEMOS = {
    "public-sector": {
        "productName": "Public Sector HossAgent",
        "division": "Public Sector",
        "theme": "public",
        "headline": "Watch program noise become a defensible pursuit posture.",
        "intro": "HossAgent follows one synthetic federal opportunity from first signal through qualification, partner posture, and an operator-owned pursuit decision.",
        "workspace": "Contested Logistics / CSO-27",
        "workspaceMeta": "PUBLIC-SECTOR PURSUIT CELL",
        "overviewUrl": "/#public-sector",
        "boundary": "Synthetic opportunity. No live procurement data, bid, or partner claim.",
        "finishLabel": "Evidence-qualified pursuit",
        "finishTitle": "A pursuit packet the team can defend.",
        "finishCta": "Discuss a public-sector pilot",
        "steps": [
            {
                "navTitle": "Detect the signal",
                "navMeta": "Solicitation + budget evidence",
                "label": "01 · Observe",
                "caption": "Start with source-backed program evidence, not a keyword hit dressed up as pipeline.",
                "state": "Observing",
                "kicker": "Opportunity detection",
                "title": "Connect the notice to a funded mission need.",
                "description": "A synthetic Air Force notice mentions contested-logistics decision support. HossAgent resolves the issuing office, mission language, vehicle, and budget context before treating it as an opportunity.",
                "sourceTitle": "Evidence entering the pursuit record",
                "sources": [
                    {"kind": "SAM", "name": "CSO-27 notice", "meta": "Primary source · posted 06 Aug", "status": "Verified"},
                    {"kind": "BUD", "name": "PE 0605031F", "meta": "FY27 request · logistics C2", "status": "Corroborates"},
                    {"kind": "STR", "name": "AFMC digital strategy", "meta": "Policy context only", "status": "Context"},
                ],
                "metrics": [
                    {"label": "Source confidence", "value": "92%", "detail": "2 primary sources"},
                    {"label": "Response window", "value": "24d", "detail": "Concept paper"},
                    {"label": "Funding signal", "value": "Present", "detail": "Request line matched"},
                ],
                "records": [
                    {"label": "Customer", "value": "AFMC / Logistics Directorate", "status": "Resolved"},
                    {"label": "Need", "value": "Decision support for disrupted sustainment", "status": "Explicit"},
                    {"label": "Acquisition path", "value": "Commercial Solutions Opening", "status": "Open"},
                ],
                "recommendationLabel": "System posture",
                "recommendation": "Advance to qualification.",
                "recommendationDetail": "The signal is tied to a real notice, mission need, and plausible funding context.",
                "guardrailLabel": "Fake-pursuit guardrail",
                "guardrail": "PASS · primary evidence present",
                "guardrailDetail": "A strategy document alone would remain watch-only.",
                "guardrailTone": "pass",
                "actionLabel": "Build opportunity record",
                "toast": "Opportunity record opened · CSO-27",
            },
            {
                "navTitle": "Qualify the pursuit",
                "navMeta": "Fit + timing + access",
                "label": "02 · Qualify",
                "caption": "Qualification makes the gaps visible before enthusiasm becomes a bid decision.",
                "state": "Qualifying",
                "kicker": "Pursuit qualification",
                "title": "Score fit without hiding the unknowns.",
                "description": "The engine measures mission fit, delivery readiness, contracting access, timing, and evidence quality against HossAgent's declared pursuit rules.",
                "sourceTitle": "Qualification factors",
                "sources": [
                    {"kind": "FIT", "name": "Mission analytics alignment", "meta": "Current capability map", "status": "Strong"},
                    {"kind": "DEL", "name": "90-day prototype path", "meta": "Existing deployable stack", "status": "Plausible"},
                    {"kind": "ACC", "name": "Direct vehicle access", "meta": "No prime position", "status": "Gap"},
                ],
                "metrics": [
                    {"label": "Mission fit", "value": "88", "detail": "Strong"},
                    {"label": "Access", "value": "42", "detail": "Partner required", "tone": "warn"},
                    {"label": "Composite", "value": "71", "detail": "Conditional qualify"},
                ],
                "records": [
                    {"label": "Must-have", "value": "Disconnected operations", "status": "Supported"},
                    {"label": "Blocker", "value": "Vehicle and past-performance path", "status": "Open", "tone": "warn"},
                    {"label": "Unknown", "value": "Incumbent data rights", "status": "Question"},
                ],
                "recommendationLabel": "Qualification result",
                "recommendation": "Conditional qualify.",
                "recommendationDetail": "Mission fit is real; contracting access must be solved through a credible partner.",
                "guardrailLabel": "Fake-pursuit guardrail",
                "guardrail": "HOLD · no direct access",
                "guardrailDetail": "The engine blocks a solo pursuit posture until an access path is evidenced.",
                "guardrailTone": "hold",
                "actionLabel": "Map partner paths",
                "toast": "Conditional qualification recorded · access gap retained",
            },
            {
                "navTitle": "Map partner posture",
                "navMeta": "Prime + role + evidence",
                "label": "03 · Partner",
                "caption": "A partner name is not a strategy. HossAgent ties each path to access, role, and mutual value.",
                "state": "Mapping",
                "kicker": "Partner posture",
                "title": "Find the credible route into the work.",
                "description": "HossAgent compares synthetic primes against vehicle access, adjacent wins, technical complement, and conflicts—then explains the role HossAgent could actually own.",
                "sourceTitle": "Ranked partner paths",
                "sources": [
                    {"kind": "P1", "name": "Northstar Federal", "meta": "CSO access · logistics past performance", "status": "Best path"},
                    {"kind": "P2", "name": "Red Mesa Systems", "meta": "Edge integration · vehicle pending", "status": "Alternate"},
                    {"kind": "P3", "name": "Atlas Mission Tech", "meta": "Incumbent adjacency · role conflict", "status": "Watch"},
                ],
                "metrics": [
                    {"label": "Access confidence", "value": "86%", "detail": "Northstar"},
                    {"label": "Role clarity", "value": "High", "detail": "Analytics layer"},
                    {"label": "Conflict risk", "value": "Low", "detail": "No overlap"},
                ],
                "records": [
                    {"label": "Proposed role", "value": "Mission analytics subcontractor", "status": "Defensible"},
                    {"label": "Prime value", "value": "Faster evidence-to-decision loop", "status": "Specific"},
                    {"label": "Next proof", "value": "Confirm data-rights boundary", "status": "Required"},
                ],
                "recommendationLabel": "Partner recommendation",
                "recommendation": "Shape with Northstar Federal.",
                "recommendationDetail": "The partner supplies vehicle and customer access; HossAgent owns the evidence and decision layer.",
                "guardrailLabel": "Partner-claim guardrail",
                "guardrail": "PASS · role and value explicit",
                "guardrailDetail": "No teaming or relationship is represented as confirmed.",
                "guardrailTone": "pass",
                "actionLabel": "Build pursuit posture",
                "toast": "Best partner path selected · claim boundary preserved",
            },
            {
                "navTitle": "Set pursuit posture",
                "navMeta": "Pursue + conditions",
                "label": "04 · Posture",
                "caption": "The attractive opportunity stays bounded by explicit no-go conditions.",
                "state": "Reasoning",
                "kicker": "Pursuit posture",
                "title": "Recommend a move—and the reasons to stop.",
                "description": "The engine combines evidence strength, fit, access, partner posture, economics, and open questions into a conditional recommendation.",
                "sourceTitle": "Decision conditions",
                "sources": [
                    {"kind": "GO", "name": "Mission and solution fit", "meta": "Score above declared threshold", "status": "Met"},
                    {"kind": "GO", "name": "Credible access path", "meta": "Northstar path evidenced", "status": "Met"},
                    {"kind": "STOP", "name": "Data-rights boundary", "meta": "Must resolve before submission", "status": "Open"},
                ],
                "metrics": [
                    {"label": "Pursuit score", "value": "79", "detail": "Qualified"},
                    {"label": "Evidence", "value": "A−", "detail": "Traceable"},
                    {"label": "No-go gates", "value": "1", "detail": "Before submit", "tone": "warn"},
                ],
                "records": [
                    {"label": "Posture", "value": "Pursue with partner", "status": "Recommended"},
                    {"label": "Investment", "value": "Discovery + concept paper only", "status": "Bounded"},
                    {"label": "Stop if", "value": "Data access requires ownership transfer", "status": "Explicit", "tone": "warn"},
                ],
                "recommendationLabel": "System recommendation",
                "recommendation": "Pursue conditionally.",
                "recommendationDetail": "Invest in shaping and a concept paper; do not cross the data-rights no-go gate.",
                "guardrailLabel": "Fake-pursuit guardrail",
                "guardrail": "CONDITIONAL · one no-go gate open",
                "guardrailDetail": "Submission remains blocked until the named condition is cleared.",
                "guardrailTone": "hold",
                "actionLabel": "Send to operator review",
                "toast": "Conditional posture ready for pursuit owner",
            },
            {
                "navTitle": "Record the decision",
                "navMeta": "Operator bid / no-bid",
                "label": "05 · Decide",
                "caption": "HossAgent recommends the posture. A named pursuit owner authorizes the investment.",
                "state": "Reviewing",
                "kicker": "Operator authority",
                "title": "Approve the next investment—not an imaginary win.",
                "description": "The pursuit owner accepts a narrow shaping motion, assigns the unresolved proof task, and retains the submission gate.",
                "sourceTitle": "Decision record",
                "sources": [
                    {"kind": "OWN", "name": "Jordan Lee", "meta": "Pursuit owner", "status": "Named"},
                    {"kind": "ACT", "name": "Partner discovery", "meta": "Northstar technical lead", "status": "Approved"},
                    {"kind": "GATE", "name": "Concept submission", "meta": "Blocked pending data rights", "status": "Retained"},
                ],
                "metrics": [
                    {"label": "Decision", "value": "Shape", "detail": "Conditional"},
                    {"label": "Owner", "value": "J. Lee", "detail": "Operator"},
                    {"label": "Next review", "value": "10d", "detail": "Gate check"},
                ],
                "records": [
                    {"label": "Approved spend", "value": "16 pursuit hours", "status": "Bounded"},
                    {"label": "Required proof", "value": "Customer data-rights answer", "status": "Assigned"},
                    {"label": "Submission authority", "value": "Pursuit owner only", "status": "Retained"},
                ],
                "recommendationLabel": "Recorded disposition",
                "recommendation": "SHAPE · do not submit.",
                "recommendationDetail": "The team may validate the partner path while the material no-go condition remains open.",
                "guardrailLabel": "Operator-control guardrail",
                "guardrail": "PASS · submission remains blocked",
                "guardrailDetail": "Automation cannot turn shaping approval into a bid approval.",
                "guardrailTone": "pass",
                "actionLabel": "Sign pursuit decision",
                "toast": "Decision signed by pursuit owner · submission gate retained",
            },
            {
                "navTitle": "Export the packet",
                "navMeta": "Evidence + posture + tasks",
                "label": "06 · Packet",
                "caption": "The result leaves the dashboard as a pursuit packet with sources, gaps, posture, and ownership.",
                "state": "Complete",
                "kicker": "Pursuit artifact",
                "title": "Give the team one source of pursuit truth.",
                "description": "A reproducible packet carries the evidence record, qualification logic, partner hypothesis, decision boundary, and assigned next actions into the pursuit rhythm.",
                "sourceTitle": "Pursuit packet contents",
                "sources": [
                    {"kind": "PDF", "name": "Executive pursuit brief", "meta": "Sources + recommendation", "status": "Ready"},
                    {"kind": "LOG", "name": "Qualification record", "meta": "Scores + open conditions", "status": "Ready"},
                    {"kind": "TASK", "name": "10-day action plan", "meta": "Owners + review gate", "status": "Ready"},
                ],
                "metrics": [
                    {"label": "Disposition", "value": "SHAPE", "detail": "Do not submit"},
                    {"label": "Sources", "value": "7", "detail": "Traceable"},
                    {"label": "Open gates", "value": "1", "detail": "Assigned"},
                ],
                "records": [
                    {"label": "Primary partner", "value": "Northstar Federal", "status": "Hypothesis"},
                    {"label": "Approved motion", "value": "Technical discovery", "status": "Owned"},
                    {"label": "Claim boundary", "value": "Synthetic · no teaming claim", "status": "Visible"},
                ],
                "recommendationLabel": "Customer artifact",
                "recommendation": "Pursuit packet ready.",
                "recommendationDetail": "Every recommendation, gap, gate, and owner travels with the underlying evidence.",
                "guardrailLabel": "Release boundary",
                "guardrail": "PASS · no external action taken",
                "guardrailDetail": "The demo creates no bid, email, partner contact, or procurement claim.",
                "guardrailTone": "pass",
                "actionLabel": "Preview pursuit packet",
                "toast": "Synthetic pursuit packet generated · no file written",
                "artifact": {"type": "PURSUIT PACKET", "decision": "SHAPE / DO NOT SUBMIT", "owner": "Jordan Lee", "reference": "CSO-27 · HA-PS-0042"},
            },
        ],
    },
    "private-sector": {
        "productName": "Private Sector HossAgent",
        "division": "Private Sector",
        "theme": "private",
        "headline": "Watch company signals become a disciplined sales motion.",
        "intro": "HossAgent follows one synthetic growth signal through company resolution, pain inference, account scoring, buyer verification, and operator-approved outreach.",
        "workspace": "Heritage Distribution / South Florida",
        "workspaceMeta": "PRIVATE-SECTOR REVENUE CELL",
        "overviewUrl": "/#private-sector",
        "boundary": "Synthetic account. No live buyer data, CRM write, email, or sales claim.",
        "finishLabel": "Buyer-verified motion",
        "finishTitle": "A sales brief that earns the right to outreach.",
        "finishCta": "Discuss a private-sector pilot",
        "steps": [
            {
                "navTitle": "Detect growth",
                "navMeta": "Hiring + facility + filings",
                "label": "01 · Detect",
                "caption": "The engine assembles a company event from independent sources before it infers commercial intent.",
                "state": "Observing",
                "kicker": "Company signal",
                "title": "Turn scattered growth clues into one account event.",
                "description": "A synthetic distributor opens a South Florida hub. HossAgent connects the facility permit, operations hiring, and corporate filing to the same legal company.",
                "sourceTitle": "Corroborating company evidence",
                "sources": [
                    {"kind": "PERM", "name": "Warehouse improvement permit", "meta": "County record · 182K sq ft", "status": "Primary"},
                    {"kind": "JOB", "name": "18 operations openings", "meta": "Company careers domain", "status": "Primary"},
                    {"kind": "FILE", "name": "Florida foreign registration", "meta": "Legal entity matched", "status": "Verified"},
                ],
                "metrics": [
                    {"label": "Signal confidence", "value": "94%", "detail": "3 sources"},
                    {"label": "Freshness", "value": "6d", "detail": "Current"},
                    {"label": "Event", "value": "Expansion", "detail": "New hub"},
                ],
                "records": [
                    {"label": "Company", "value": "Heritage Distribution Group", "status": "Resolved"},
                    {"label": "Domain", "value": "heritagedistribution.example", "status": "Matched"},
                    {"label": "Operating change", "value": "South Florida hub launch", "status": "Corroborated"},
                ],
                "recommendationLabel": "Signal disposition",
                "recommendation": "Open an account hypothesis.",
                "recommendationDetail": "The expansion is real enough to investigate; it is not yet a reason to contact anyone.",
                "guardrailLabel": "Outbound guardrail",
                "guardrail": "BLOCKED · no buyer resolved",
                "guardrailDetail": "Company evidence may start research, never outreach.",
                "guardrailTone": "block",
                "actionLabel": "Resolve account",
                "toast": "Company event linked · outreach remains blocked",
            },
            {
                "navTitle": "Infer the pain",
                "navMeta": "Evidence → operating hypothesis",
                "label": "02 · Infer",
                "caption": "HossAgent distinguishes observed facts from the pain hypothesis they support.",
                "state": "Reasoning",
                "kicker": "Pain inference",
                "title": "Explain what the expansion likely makes harder.",
                "description": "The engine maps the observed hub launch, compressed hiring window, and multi-site footprint to a testable operating hypothesis—without presenting an estimate as fact.",
                "sourceTitle": "Fact-to-hypothesis chain",
                "sources": [
                    {"kind": "FACT", "name": "New 182K sq ft hub", "meta": "Observed in permit", "status": "Known"},
                    {"kind": "FACT", "name": "18 roles in 45 days", "meta": "Observed on company site", "status": "Known"},
                    {"kind": "INFER", "name": "Ramp coordination pressure", "meta": "Model inference", "status": "Hypothesis"},
                ],
                "metrics": [
                    {"label": "Pain confidence", "value": "78%", "detail": "Testable"},
                    {"label": "Urgency", "value": "High", "detail": "45-day ramp"},
                    {"label": "Known / inferred", "value": "2 / 1", "detail": "Separated"},
                ],
                "records": [
                    {"label": "Likely pain", "value": "Cross-site operating visibility", "status": "Inferred"},
                    {"label": "Evidence", "value": "Concurrent facility and labor ramp", "status": "Observed"},
                    {"label": "Unknown", "value": "Current planning system", "status": "Validate"},
                ],
                "recommendationLabel": "Commercial hypothesis",
                "recommendation": "Test operational-ramp pain.",
                "recommendationDetail": "Lead with the observed expansion and a question—not an invented diagnosis.",
                "guardrailLabel": "Truth guardrail",
                "guardrail": "PASS · inference labeled",
                "guardrailDetail": "The system keeps sourced facts and modeled pain in separate fields.",
                "guardrailTone": "pass",
                "actionLabel": "Score account readiness",
                "toast": "Pain hypothesis recorded · facts remain distinct",
            },
            {
                "navTitle": "Score readiness",
                "navMeta": "Fit + timing + evidence",
                "label": "03 · Score",
                "caption": "Readiness rewards fit and timing but penalizes unresolved buying authority.",
                "state": "Scoring",
                "kicker": "Account qualification",
                "title": "Decide whether this account deserves focused effort.",
                "description": "HossAgent scores the account against declared ICP, trigger timing, pain evidence, solution fit, and contactability—not against a generic intent score.",
                "sourceTitle": "Readiness dimensions",
                "sources": [
                    {"kind": "ICP", "name": "Multi-site distributor", "meta": "$250M–$1B revenue band", "status": "Strong"},
                    {"kind": "TIME", "name": "Active expansion window", "meta": "Operational ramp underway", "status": "Strong"},
                    {"kind": "BUY", "name": "Buying committee", "meta": "Economic buyer unresolved", "status": "Gap"},
                ],
                "metrics": [
                    {"label": "ICP fit", "value": "91", "detail": "Strong"},
                    {"label": "Timing", "value": "88", "detail": "Active"},
                    {"label": "Readiness", "value": "74", "detail": "Research", "tone": "warn"},
                ],
                "records": [
                    {"label": "Motion", "value": "Account research", "status": "Allowed"},
                    {"label": "Message angle", "value": "Ramp visibility", "status": "Supported"},
                    {"label": "Outbound", "value": "No verified buyer", "status": "Blocked", "tone": "warn"},
                ],
                "recommendationLabel": "Readiness result",
                "recommendation": "Prioritize research, not outreach.",
                "recommendationDetail": "The account is timely and on-profile, but HossAgent has not earned a buyer conversation yet.",
                "guardrailLabel": "Outbound guardrail",
                "guardrail": "BLOCKED · economic buyer unknown",
                "guardrailDetail": "A high account score cannot override the buyer requirement.",
                "guardrailTone": "block",
                "actionLabel": "Resolve buying role",
                "toast": "Account prioritized · outbound still blocked",
            },
            {
                "navTitle": "Verify the buyer",
                "navMeta": "Role + identity + channel",
                "label": "04 · Verify",
                "caption": "A real company is not enough. The engine verifies a relevant decision-maker and a permitted channel.",
                "state": "Verifying",
                "kicker": "Buyer resolution",
                "title": "Earn the right to put a message in front of someone.",
                "description": "A synthetic VP of Network Operations is resolved through the company domain, current role evidence, and a verified work channel, then checked against suppression rules.",
                "sourceTitle": "Buyer evidence",
                "sources": [
                    {"kind": "ROLE", "name": "Maya Chen · VP Network Operations", "meta": "Current company leadership page", "status": "Verified"},
                    {"kind": "MAIL", "name": "Work email pattern", "meta": "Domain-level verification", "status": "Verified"},
                    {"kind": "SAFE", "name": "Suppression and DNC check", "meta": "No matching restriction", "status": "Clear"},
                ],
                "metrics": [
                    {"label": "Identity", "value": "96%", "detail": "Current role"},
                    {"label": "Role relevance", "value": "High", "detail": "Owns network ops"},
                    {"label": "Channel", "value": "Verified", "detail": "Work email"},
                ],
                "records": [
                    {"label": "Buyer", "value": "Maya Chen", "status": "Real"},
                    {"label": "Why this buyer", "value": "Owns multi-site operating model", "status": "Relevant"},
                    {"label": "Permission state", "value": "Review-mode outreach only", "status": "Controlled"},
                ],
                "recommendationLabel": "Buyer resolution",
                "recommendation": "Buyer verified for operator review.",
                "recommendationDetail": "The role matches the hypothesized pain and the channel passes configured safety checks.",
                "guardrailLabel": "Outbound guardrail",
                "guardrail": "PASS · buyer and channel verified",
                "guardrailDetail": "Verification enables drafting; it does not send anything.",
                "guardrailTone": "pass",
                "actionLabel": "Draft sales motion",
                "toast": "Buyer verified · review-mode draft unlocked",
            },
            {
                "navTitle": "Approve the motion",
                "navMeta": "Operator review + boundaries",
                "label": "05 · Approve",
                "caption": "The operator reviews why this buyer, why now, and exactly which claims the message may make.",
                "state": "Reviewing",
                "kicker": "Operator sales decision",
                "title": "Approve a relevant message—not an automated nuisance.",
                "description": "The draft cites the observable expansion, frames the pain as a question, and asks for a low-friction conversation. The operator controls whether it enters the outbound queue.",
                "sourceTitle": "Draft review record",
                "sources": [
                    {"kind": "WHY", "name": "Why now", "meta": "Active South Florida hub ramp", "status": "Sourced"},
                    {"kind": "WHO", "name": "Why Maya", "meta": "Network operations ownership", "status": "Sourced"},
                    {"kind": "COPY", "name": "Claim review", "meta": "No invented pain or relationship", "status": "Clean"},
                ],
                "metrics": [
                    {"label": "Motion", "value": "1:1", "detail": "Operator reviewed"},
                    {"label": "Claims", "value": "3", "detail": "All sourced"},
                    {"label": "Send state", "value": "Draft", "detail": "No-send demo"},
                ],
                "records": [
                    {"label": "Opening", "value": "Reference the verified hub expansion", "status": "Approved"},
                    {"label": "Question", "value": "Ask about cross-site ramp visibility", "status": "Approved"},
                    {"label": "Authority", "value": "Revenue operator", "status": "Operator"},
                ],
                "recommendationLabel": "Recorded decision",
                "recommendation": "Approve one review-mode draft.",
                "recommendationDetail": "The message is relevant, bounded, and assigned to a named operator for final send control.",
                "guardrailLabel": "Operator-control guardrail",
                "guardrail": "PASS · no autonomous send",
                "guardrailDetail": "The demo cannot queue, schedule, or transmit the message.",
                "guardrailTone": "pass",
                "actionLabel": "Sign motion approval",
                "toast": "Sales motion approved · no message sent",
            },
            {
                "navTitle": "Export the brief",
                "navMeta": "Evidence + buyer + message",
                "label": "06 · Brief",
                "caption": "The handoff gives sales the complete reason to act, not another anonymous lead row.",
                "state": "Complete",
                "kicker": "Account artifact",
                "title": "Deliver a buyer-ready account brief.",
                "description": "The artifact packages source evidence, known-versus-inferred pain, readiness, buyer provenance, approved message boundaries, and the operator decision.",
                "sourceTitle": "Account brief contents",
                "sources": [
                    {"kind": "PDF", "name": "Buyer-ready account brief", "meta": "Evidence + decision chain", "status": "Ready"},
                    {"kind": "COPY", "name": "Approved message draft", "meta": "Review mode · unsent", "status": "Ready"},
                    {"kind": "LOG", "name": "Source and approval log", "meta": "Reproducible record", "status": "Ready"},
                ],
                "metrics": [
                    {"label": "Readiness", "value": "86", "detail": "Buyer verified"},
                    {"label": "Buyer", "value": "1", "detail": "Role matched"},
                    {"label": "Send state", "value": "UNSENT", "detail": "Operator control"},
                ],
                "records": [
                    {"label": "Account", "value": "Heritage Distribution Group", "status": "Resolved"},
                    {"label": "Buyer", "value": "Maya Chen · VP Network Operations", "status": "Verified"},
                    {"label": "Approved motion", "value": "One review-mode discovery email", "status": "Bounded"},
                ],
                "recommendationLabel": "Customer artifact",
                "recommendation": "Account brief ready.",
                "recommendationDetail": "Sales can see why this account, why this buyer, why now, and what the evidence does not prove.",
                "guardrailLabel": "Release boundary",
                "guardrail": "PASS · no external action taken",
                "guardrailDetail": "The walkthrough creates no CRM record, email, contact, or commercial claim.",
                "guardrailTone": "pass",
                "actionLabel": "Preview account brief",
                "toast": "Synthetic account brief generated · no file written",
                "artifact": {"type": "ACCOUNT INTELLIGENCE BRIEF", "decision": "APPROVED DRAFT / UNSENT", "owner": "Revenue Operator", "reference": "HDG-SFL · HA-B2B-0186"},
            },
        ],
    },
    "property-intelligence": {
        "productName": "Property Intelligence",
        "division": "Property Intelligence",
        "theme": "property",
        "headline": "Watch a property event become an owner-qualified motion.",
        "intro": "HossAgent follows one synthetic permit through parcel matching, owner resolution, channel verification, service qualification, and operator approval.",
        "workspace": "7421 Harbor Pine Drive / Roof Permit",
        "workspaceMeta": "PROPERTY INTELLIGENCE CELL",
        "overviewUrl": "/#property-intelligence",
        "boundary": "Synthetic property and owner. No live parcel, contact, outreach, or service claim.",
        "finishLabel": "Owner-qualified opportunity",
        "finishTitle": "A property brief built for responsible action.",
        "finishCta": "Discuss a property pilot",
        "steps": [
            {
                "navTitle": "Detect the event",
                "navMeta": "Permit + source provenance",
                "label": "01 · Detect",
                "caption": "The motion begins with a source-backed property event, not an address scraped out of context.",
                "state": "Observing",
                "kicker": "Property event",
                "title": "Capture the event with its jurisdiction and source.",
                "description": "A synthetic county permit records a re-roof at 7421 Harbor Pine Drive. HossAgent preserves the filing date, permit class, contractor status, and issuing jurisdiction.",
                "sourceTitle": "Primary event evidence",
                "sources": [
                    {"kind": "PERM", "name": "Broward permit BR-27-18422", "meta": "Re-roof · filed 05 Aug", "status": "Primary"},
                    {"kind": "ADDR", "name": "7421 Harbor Pine Drive", "meta": "Normalized situs address", "status": "Parsed"},
                    {"kind": "SCOPE", "name": "Residential roof replacement", "meta": "Declared permit scope", "status": "Observed"},
                ],
                "metrics": [
                    {"label": "Source confidence", "value": "99%", "detail": "County record"},
                    {"label": "Event age", "value": "2d", "detail": "Fresh"},
                    {"label": "Match state", "value": "Pending", "detail": "Parcel next"},
                ],
                "records": [
                    {"label": "Event", "value": "Residential re-roof permit", "status": "Observed"},
                    {"label": "Applicant", "value": "Sunline Roofing LLC", "status": "On filing"},
                    {"label": "Owner", "value": "Not established by permit", "status": "Unknown"},
                ],
                "recommendationLabel": "Event disposition",
                "recommendation": "Advance to parcel match.",
                "recommendationDetail": "The permit is real; the property and owner relationship are not yet proven.",
                "guardrailLabel": "Owner-outreach guardrail",
                "guardrail": "BLOCKED · owner unknown",
                "guardrailDetail": "A permit applicant or contractor is never assumed to be the owner.",
                "guardrailTone": "block",
                "actionLabel": "Match the parcel",
                "toast": "Permit normalized · owner outreach blocked",
            },
            {
                "navTitle": "Match the property",
                "navMeta": "Address + parcel + jurisdiction",
                "label": "02 · Match",
                "caption": "HossAgent resolves the physical property before attempting to resolve the owner behind it.",
                "state": "Matching",
                "kicker": "Parcel resolution",
                "title": "Prove which parcel the event belongs to.",
                "description": "The normalized address is joined to the county parcel, legal description, land use, and homestead state. An adjacent parcel with a similar street number is rejected.",
                "sourceTitle": "Property match evidence",
                "sources": [
                    {"kind": "GIS", "name": "Parcel 5041-28-09-1170", "meta": "County GIS situs match", "status": "Exact"},
                    {"kind": "TAX", "name": "2026 assessment record", "meta": "Legal description aligned", "status": "Matched"},
                    {"kind": "ALT", "name": "7421 Harbor Pines Court", "meta": "Adjacent candidate", "status": "Rejected"},
                ],
                "metrics": [
                    {"label": "Parcel confidence", "value": "98%", "detail": "Exact match"},
                    {"label": "Candidates", "value": "2", "detail": "1 rejected"},
                    {"label": "Land use", "value": "SFR", "detail": "Residential"},
                ],
                "records": [
                    {"label": "Parcel", "value": "5041-28-09-1170", "status": "Resolved"},
                    {"label": "Property", "value": "Single-family residence · 1998", "status": "Recorded"},
                    {"label": "Event match", "value": "Permit ↔ parcel", "status": "Exact"},
                ],
                "recommendationLabel": "Property resolution",
                "recommendation": "Parcel match accepted.",
                "recommendationDetail": "The event is attached to one property with an explicit rejected alternative.",
                "guardrailLabel": "Property-match guardrail",
                "guardrail": "PASS · ambiguity resolved",
                "guardrailDetail": "Only an exact jurisdiction and parcel match may advance.",
                "guardrailTone": "pass",
                "actionLabel": "Resolve ownership",
                "toast": "Parcel resolved · rejected alternative logged",
            },
            {
                "navTitle": "Resolve the owner",
                "navMeta": "Deed + tax roll + entity",
                "label": "03 · Resolve",
                "caption": "Ownership is a provenance problem: current record, vesting, mailing address, and confidence all travel together.",
                "state": "Resolving",
                "kicker": "Owner identity",
                "title": "Separate the legal owner from occupants and contractors.",
                "description": "The county tax roll and latest deed identify Harbor Pine Family Trust. HossAgent resolves the trustee record and flags that occupancy remains unproven.",
                "sourceTitle": "Ownership evidence",
                "sources": [
                    {"kind": "DEED", "name": "Warranty deed OR-119842", "meta": "Vested to family trust", "status": "Current"},
                    {"kind": "TAX", "name": "2026 tax roll", "meta": "Mailing address aligned", "status": "Matched"},
                    {"kind": "TRST", "name": "Elena Marquez · trustee", "meta": "Public trustee record", "status": "Resolved"},
                ],
                "metrics": [
                    {"label": "Owner confidence", "value": "93%", "detail": "2 records"},
                    {"label": "Vesting", "value": "Trust", "detail": "Current"},
                    {"label": "Occupancy", "value": "Unknown", "detail": "Not assumed", "tone": "warn"},
                ],
                "records": [
                    {"label": "Legal owner", "value": "Harbor Pine Family Trust", "status": "Verified"},
                    {"label": "Trustee", "value": "Elena Marquez", "status": "Resolved"},
                    {"label": "Resident", "value": "Not established", "status": "Unknown"},
                ],
                "recommendationLabel": "Owner resolution",
                "recommendation": "Owner identity resolved.",
                "recommendationDetail": "The trustee is the relevant contact; the system makes no occupancy claim.",
                "guardrailLabel": "Owner-outreach guardrail",
                "guardrail": "HOLD · channel not verified",
                "guardrailDetail": "A resolved owner still cannot be contacted through an unverified channel.",
                "guardrailTone": "hold",
                "actionLabel": "Verify owner channel",
                "toast": "Legal owner resolved · channel verification required",
            },
            {
                "navTitle": "Verify the channel",
                "navMeta": "Provenance + suppression",
                "label": "04 · Verify",
                "caption": "The engine checks that the channel belongs to the resolved owner and is eligible for the approved motion.",
                "state": "Verifying",
                "kicker": "Contactability",
                "title": "Verify a responsible route to the owner.",
                "description": "A synthetic owner phone is tied to the trustee through two public records, then checked for type, freshness, suppression, and do-not-contact restrictions.",
                "sourceTitle": "Channel evidence",
                "sources": [
                    {"kind": "TEL", "name": "Mobile ending 0184", "meta": "Two-source trustee match", "status": "Verified"},
                    {"kind": "AGE", "name": "Observed 31 days ago", "meta": "Within freshness policy", "status": "Current"},
                    {"kind": "SAFE", "name": "DNC + suppression check", "meta": "No restriction found", "status": "Clear"},
                ],
                "metrics": [
                    {"label": "Channel confidence", "value": "91%", "detail": "Owner matched"},
                    {"label": "Type", "value": "Mobile", "detail": "Verified"},
                    {"label": "Safety", "value": "Clear", "detail": "Policy checked"},
                ],
                "records": [
                    {"label": "Contact", "value": "Elena Marquez · trustee", "status": "Relevant"},
                    {"label": "Channel", "value": "Verified mobile · •••• 0184", "status": "Eligible"},
                    {"label": "Permission", "value": "Operator review required", "status": "Controlled"},
                ],
                "recommendationLabel": "Contactability result",
                "recommendation": "Channel eligible for review.",
                "recommendationDetail": "Identity, relevance, provenance, freshness, and safety checks all pass.",
                "guardrailLabel": "Owner-outreach guardrail",
                "guardrail": "PASS · owner-channel link verified",
                "guardrailDetail": "Verification unlocks a draft only; it never initiates contact.",
                "guardrailTone": "pass",
                "actionLabel": "Qualify the motion",
                "toast": "Owner channel verified · no contact initiated",
            },
            {
                "navTitle": "Approve the motion",
                "navMeta": "Need + fit + operator review",
                "label": "05 · Approve",
                "caption": "The event may create relevance, but the operator decides whether the service motion is appropriate.",
                "state": "Reviewing",
                "kicker": "Operator decision",
                "title": "Approve a bounded owner conversation.",
                "description": "The motion references only the public permit, offers a permit-adjacent inspection conversation, and avoids claims about damage, urgency, residency, or insurance.",
                "sourceTitle": "Motion review",
                "sources": [
                    {"kind": "WHY", "name": "Why now", "meta": "Recently filed re-roof permit", "status": "Sourced"},
                    {"kind": "OFFER", "name": "Permit-adjacent inspection", "meta": "Service fit declared", "status": "Relevant"},
                    {"kind": "CLAIM", "name": "Prohibited assumptions", "meta": "No damage or insurance claim", "status": "Clean"},
                ],
                "metrics": [
                    {"label": "Property fit", "value": "84", "detail": "Qualified"},
                    {"label": "Owner confidence", "value": "93%", "detail": "Verified"},
                    {"label": "Motion", "value": "Call", "detail": "Operator-only"},
                ],
                "records": [
                    {"label": "Approved opening", "value": "Reference the public permit", "status": "Bounded"},
                    {"label": "Prohibited", "value": "Damage, insurance, or urgency claims", "status": "Blocked"},
                    {"label": "Authority", "value": "Property operator", "status": "Operator"},
                ],
                "recommendationLabel": "Recorded decision",
                "recommendation": "Approve one owner conversation.",
                "recommendationDetail": "The owner, channel, relevance, and permitted claims are explicit and operator-reviewed.",
                "guardrailLabel": "Operator-control guardrail",
                "guardrail": "PASS · no autonomous outreach",
                "guardrailDetail": "The demo cannot dial, message, queue, or schedule contact.",
                "guardrailTone": "pass",
                "actionLabel": "Sign motion approval",
                "toast": "Property motion approved · no contact initiated",
            },
            {
                "navTitle": "Export the brief",
                "navMeta": "Property + owner + motion",
                "label": "06 · Brief",
                "caption": "The final brief keeps the event, parcel, owner, channel, and approved claims connected to provenance.",
                "state": "Complete",
                "kicker": "Property artifact",
                "title": "Deliver an owner-qualified property brief.",
                "description": "The artifact carries the primary event, exact parcel match, ownership chain, verified channel, service reasoning, prohibited claims, and operator decision.",
                "sourceTitle": "Property brief contents",
                "sources": [
                    {"kind": "PDF", "name": "Owner-qualified property brief", "meta": "Evidence + motion", "status": "Ready"},
                    {"kind": "MAP", "name": "Parcel and ownership chain", "meta": "Alternatives + provenance", "status": "Ready"},
                    {"kind": "SAFE", "name": "Channel and claim controls", "meta": "Approval record", "status": "Ready"},
                ],
                "metrics": [
                    {"label": "Parcel", "value": "98%", "detail": "Exact match"},
                    {"label": "Owner", "value": "93%", "detail": "Verified"},
                    {"label": "Contact state", "value": "NONE", "detail": "Operator control"},
                ],
                "records": [
                    {"label": "Property", "value": "7421 Harbor Pine Drive", "status": "Matched"},
                    {"label": "Owner", "value": "Harbor Pine Family Trust", "status": "Verified"},
                    {"label": "Approved motion", "value": "One permit-adjacent owner call", "status": "Bounded"},
                ],
                "recommendationLabel": "Customer artifact",
                "recommendation": "Property brief ready.",
                "recommendationDetail": "The operator can see what is fact, what is inferred, who owns the property, and exactly what is allowed.",
                "guardrailLabel": "Release boundary",
                "guardrail": "PASS · no external action taken",
                "guardrailDetail": "The walkthrough creates no parcel update, contact, message, dial, or property claim.",
                "guardrailTone": "pass",
                "actionLabel": "Preview property brief",
                "toast": "Synthetic property brief generated · no file written",
                "artifact": {"type": "OWNER-QUALIFIED PROPERTY BRIEF", "decision": "APPROVED MOTION / NO CONTACT", "owner": "Property Operator", "reference": "BR-27-18422 · HA-PI-0742"},
            },
        ],
    },
}


def get_product_demo(slug: str):
    """Return a configured public demo, or ``None`` for unsupported slugs."""
    return PRODUCT_DEMOS.get(slug)


def serialize_product_demo(slug: str) -> str:
    """Serialize a demo safely for embedding inside an HTML script element."""
    demo = get_product_demo(slug)
    if demo is None:
        raise KeyError(slug)
    return json.dumps(demo, separators=(",", ":")).replace("</", "<\\/")
